Update tsconfig.1.json
ERROR in [at-loader] ./src/polyfills.ts:3:1
 TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./src/polyfills.ts:5:5
TS2304: Cannot find name 'process'.

ERROR in [at-loader] ./src/polyfills.ts:10:3
TS2304: Cannot find name 'require'.

For fixing these type of issues.