Eliminate "error TS6064" while executing tsc --watch
Below command given in QuickStart.html, throws error when executed. Therefore suggesting an extra option to eliminate it. 

tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts
error TS6064: Option 'experimentalDecorators' must also be specified when option 'emitDecoratorMetadata' is specified.
message TS6042: Compilation complete. Watching for file changes.
  
Works correctly with additional option.
tsc --watch -m commonjs -t es5 --emitDecoratorMetadata --experimentalDecorators app.ts
message TS6042: Compilation complete. Watching for file changes.